tunnel: 8f05d360-d559-41ec-a716-5c8879a8d15d
credentials-file: /Users/r.brederode/.cloudflared/8f05d360-d559-41ec-a716-5c8879a8d15d.json

ingress:
  - hostname: webhook.dmd2000.org
    service: http://localhost:5001
  - service: http_status:404
